on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          javaHome: 'C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot\bin'  # Update with your JDK 17 installation path

      - name: Create lib directory and download JUnit JAR file
        run: |
          mkdir lib
          Invoke-WebRequest -Uri 'https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar' -OutFile 'lib/junit-4.13.2.jar'

  test:
    name: Test
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          javaHome: 'C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot\bin'  # Update with your JDK 17 installation path
      
      - name: Install JUnit
        run: |
          # Commands to install JUnit
          mkdir lib
          curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
          mv junit-platform-console-standalone-1.8.2.jar lib/

      - name: Run automated tests
        run: |
          # Commands to run automated tests with JUnit
          java -jar lib/junit-platform-console-standalone-1.8.2.jar --class-path target --scan-class-path
